# This is docker-compose.yml for local development environment
# Don't forget `docker-compose build web` to update image if you update Gemfile
web:
  build: .
  links:
    - postgres
    - redis
  ports:
    - "80:80"
  # Following is development configuration
  command: rails server -b 0.0.0.0 -p 80
  environment:
    RAILS_ENV: development
  volumes_from:
    - data
webresque:
  image: railsdockerexample_web
  links:
    - redis
  volumes_from:
    - data
  environment:
    QUEUE: "*"
    # Following is development configuration
    RAILS_ENV: development
  command: rake environment resque:work
postgres:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
  volumes_from:
    - data
redis:
  image: redis
  # Open port for local development environment
  ports:
    - "6379:6379"
data:
  image: busybox
  volumes:
    - /tmp
    # For postgres
    - /var/lib/postgresql/data
    - .:/usr/src/app
