web:
  image: ubuntu:14.04
  command: /bin/sh -c "while true; do echo hello world; sleep 1; done"
  links:
    - db
    - redis
    - data
verificaiton:
  image: ubuntu:14.04
db:
  image: postgres
redis:
  image: redis
  ports:
    - 6379:6379
data:
  image: busybox