web:
  build: .
  links:
    - postgres
    - redis
  ports:
    - "80:80"
webresque:
  image: railsdockerexample_web
  links:
    - redis
  volumes_from:
    - data
  environment:
    QUEUE: "*"
  command: rake environment resque:work
postgres:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
  volumes_from:
    - data
redis:
  image: redis
data:
  image: busybox
  volumes:
    - /tmp
    # For postgres
    - /var/lib/postgresql/data
