web:
  build: .
  #image: ubuntu:14.04
  #command: /bin/sh -c "while true; do echo hello world; sleep 1; done"
  links:
    - postgres
    - redis
  ports:
    - "80:80"
webresque:
  image: railsdockerexample_web
  links:
    - redis
  environment:
    QUEUE: "*"
  command: /bin/bash -c "bundle exec rake environment resque:work"
postgres:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
redis:
  image: redis
  # Open port for local development environment
  ports:
    - "6379:6379"
