web:
  build: .
  links:
    - postgres
    - redis
  ports:
    - "80:80"
webresque:
  image: railsdockerexample_web
  links:
    - redis
  volumes_from:
    - data
  environment:
    QUEUE: "*"
  command: /bin/bash -c "bundle exec rake environment resque:work"
postgres:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
redis:
  image: redis
  # Open port for local development environment
  ports:
    - "6379:6379"
data:
  image: busybox
  volumes:
    - /tmp
